import { test } from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
delete process.env.DATABASE_URL;
delete process.env.VERCEL;
process.env.CRM_LOCAL_PATH = 'memory://';
process.env.CRM_LOCAL_DATABASE = 'true';
const db = await import('../lib/crm/database.ts');
const auth = await import('../lib/crm/auth.ts');
const repo = await import('../lib/projects/repository.ts');
const input = changes => repo.parseProject({ name: 'Test saha projesi', description: 'Gerçek proje bilgisi yerine kullanılan test kaydı.', startDate: '2026-09-15', endDate: '', published: false, ...changes });

test('project persistence, publishing, image handling and username login', async t => {
  t.after(() => db.closeDatabase());
  const onur = await auth.provisionAdmin(auth.adminAccounts[0].email, 'Test-only-password-123');
  const ahmet = await auth.provisionAdmin(auth.adminAccounts[2].email, 'Test-only-password-456');
  assert.equal((await auth.authenticate(' ONURDURAK ', 'Test-only-password-123')).id, onur.id);
  assert.equal((await auth.authenticate('ahmetcansever', 'Test-only-password-456')).id, ahmet.id);
  assert.equal(await auth.authenticate('ahmetcansever', 'wrong'), null);
  for (const change of [{ startDate: '2026-02-30' }, { endDate: '2026-09-14' }, { name: '' }, { published: 'true' }, { description: 'x'.repeat(5001) }]) assert.throws(() => input(change));
  const first = await repo.saveProject(input(), onur.id);
  assert.equal((await repo.listProjects()).length, 0, 'drafts remain private');
  assert.equal((await repo.listProjects(false)).length, 1);
  const png = await sharp({ create: { width: 64, height: 32, channels: 3, background: '#287344' } }).png().toBuffer();
  const image = await repo.addProjectImage(first.id, png);
  assert.equal(await repo.getProjectImage(image.id), undefined);
  const privateImage = await repo.getProjectImage(image.id, true);
  assert.equal((await sharp(Buffer.from(privateImage.data)).metadata()).format, 'webp');
  await assert.rejects(repo.addProjectImage(first.id, Buffer.from('<svg onload="alert(1)"></svg>')), error => error.status === 400);
  await assert.rejects(repo.addProjectImage(first.id, Buffer.alloc(3 * 1024 * 1024 + 1)), error => error.status === 413);
  await repo.saveProject(input({ published: true, endDate: '2026-10-01' }), ahmet.id, first.id);
  const published = await repo.listProjects();
  assert.equal(published.length, 1); assert.equal(published[0].images.length, 1);
  assert.ok(await repo.getProjectImage(image.id));
  const second = await repo.saveProject(input({ name: 'İkinci proje', published: true }), ahmet.id);
  await assert.rejects(repo.removeProjectImage(second.id, image.id), error => error.status === 404);
  assert.ok(await repo.getProjectImage(image.id));
  for (let i = 1; i < 12; i++) await repo.addProjectImage(first.id, png);
  await assert.rejects(repo.addProjectImage(first.id, png), error => error.status === 400);
  await repo.removeProjectImage(first.id, image.id);
  assert.equal(await repo.getProjectImage(image.id, true), undefined);
  const remainingImage = (await repo.getProject(first.id)).images[0];
  await repo.deleteProject(first.id);
  assert.equal(await repo.getProjectImage(remainingImage.id, true), undefined, 'deleting a project removes its images');
  await repo.saveProject(input({ published: false }), ahmet.id, second.id);
  assert.equal((await repo.listProjects()).length, 0);
  await db.getDatabase().prepare('CREATE ROLE project_test_anon').run();
  for (const table of ['projects', 'project_images']) await assert.rejects(db.transaction(async connection => {
    await connection.prepare('SET LOCAL ROLE project_test_anon').run();
    await connection.prepare(`SELECT * FROM ${table}`).all();
  }), error => error.code === '42501');
});
