// Published URLs remain permanent aliases. Keep destinations canonical (no chains).
export const publicRedirects = [
  { source: "/hesapla", destination: "/hesaplayici", permanent: true },
  { source: "/ges-hesaplama", destination: "/hesaplayici", permanent: true },
  { source: "/ges-kurulumu", destination: "/bolgeler", permanent: true },
  { source: "/gizlilik-politikasi", destination: "/gizlilik", permanent: true },
  { source: "/cerez-politikasi", destination: "/cerezler", permanent: true },
  { source: "/ges-kurulumu/:path+", destination: "/bolgeler/:path+", permanent: true },
  { source: "/hizmetler/gunes-enerjisi-sistemleri", destination: "/hizmetler/gunes-enerjisi", permanent: true },
  { source: "/hizmetler/cephe-tipi-uygulamalar", destination: "/hizmetler/cati-cephe", permanent: true },
  { source: "/hizmetler/projelendirme-ve-muhendislik", destination: "/hizmetler/muhendislik", permanent: true },
  { source: "/hizmetler/elektrik-altyapisi", destination: "/hizmetler/elektrik", permanent: true },
  { source: "/hizmetler/kurulum-ve-devreye-alma", destination: "/hizmetler/kurulum", permanent: true },
  { source: "/hizmetler/bakim-ve-teknik-destek", destination: "/hizmetler/bakim", permanent: true },
  { source: "/hizmetler/endustriyel-cati-ges", destination: "/hizmetler/cati-ges", permanent: true },
  { source: "/rehber/gunes-enerjisi-sistemi-nasil-calisir", destination: "/rehber/gunes-enerjisi", permanent: true },
  { source: "/rehber/gunes-paneli-nedir-nelerden-olusur", destination: "/rehber/gunes-paneli", permanent: true },
  { source: "/rehber/cati-tipi-gunes-paneli-sistemi-nedir", destination: "/rehber/cati-ges", permanent: true },
  { source: "/rehber/cephe-tipi-gunes-paneli-sistemi-nedir", destination: "/rehber/cephe-ges", permanent: true },
  { source: "/rehber/arazi-tipi-ges-nedir", destination: "/rehber/arazi-ges", permanent: true },
  { source: "/rehber/monokristal-polikristal-panel-farki", destination: "/rehber/panel-turleri", permanent: true },
  { source: "/rehber/inverter-nedir-neden-gereklidir", destination: "/rehber/inverter", permanent: true },
  { source: "/rehber/gunes-paneli-verimini-neler-etkiler", destination: "/rehber/panel-verimi", permanent: true },
  { source: "/rehber/gunes-panelleri-bulutlu-havada-calisir-mi", destination: "/rehber/bulutlu-hava", permanent: true },
  { source: "/rehber/gunes-paneli-garanti-suresi", destination: "/rehber/panel-garantisi", permanent: true },
  { source: "/rehber/kac-kw-sistem-gerekir", destination: "/rehber/sistem-gucu", permanent: true },
  { source: "/rehber/gunes-paneli-kurulum-sureci-adim-adim", destination: "/rehber/kurulum-sureci", permanent: true },
  { source: "/rehber/gunes-paneli-kurulumu-ne-kadar-surer", destination: "/rehber/kurulum-suresi", permanent: true },
  { source: "/rehber/catim-gunes-paneline-uygun-mu", destination: "/rehber/cati-uygunlugu", permanent: true },
  { source: "/rehber/gunes-paneli-catinin-statigini-etkiler-mi", destination: "/rehber/cati-statigi", permanent: true },
  { source: "/rehber/gunes-paneli-icin-izin-gerekir-mi", destination: "/rehber/kurulum-izinleri", permanent: true },
  { source: "/rehber/lisanssiz-elektrik-uretimi-nedir", destination: "/rehber/lisanssiz-uretim", permanent: true },
  { source: "/rehber/edas-baglanti-basvurusu-nasil-yapilir", destination: "/rehber/baglanti-basvurusu", permanent: true },
  { source: "/rehber/mahsuplasma-net-metering-nedir", destination: "/rehber/mahsuplasma", permanent: true },
  { source: "/rehber/sebekeye-verilen-fazla-enerji-ne-oluyor", destination: "/rehber/fazla-enerji", permanent: true },
  { source: "/rehber/gunes-paneli-fiyatini-neler-belirler", destination: "/rehber/panel-fiyatlari", permanent: true },
  { source: "/rehber/yatirimin-geri-donusu-nasil-hesaplanir", destination: "/rehber/amortisman", permanent: true },
  { source: "/rehber/gunes-panelleri-bakim-gerektirir-mi", destination: "/rehber/panel-bakimi", permanent: true },
  { source: "/rehber/kar-dolu-firtina-panellere-zarar-verir-mi", destination: "/rehber/hava-kosullari", permanent: true },
  { source: "/rehber/kacak-akim-korumasi-topraklama-neden-onemli", destination: "/rehber/topraklama", permanent: true },
  { source: "/rehber/elektrik-kesintisinde-sistem-calisir-mi", destination: "/rehber/elektrik-kesintisi", permanent: true },
  { source: "/rehber/panel-inverter-markasi-nasil-secilir", destination: "/rehber/marka-secimi", permanent: true },
  { source: "/rehber/gunes-paneli-firmasi-secerken-nelere-dikkat-edilmeli", destination: "/rehber/firma-secimi", permanent: true },
  { source: "/rehber/gunes-enerjisinin-cevresel-faydalari", destination: "/rehber/cevre", permanent: true },
  { source: "/rehber/konut-ticari-sistem-farki", destination: "/rehber/konut-ve-isletme", permanent: true },
  { source: "/rehber/half-cell-panel-nedir", destination: "/rehber/half-cell-panel", permanent: true },
  { source: "/rehber/bifacial-panel-nedir", destination: "/rehber/bifacial-panel", permanent: true },
  { source: "/rehber/string-inverter-mikroinverter-farki", destination: "/rehber/inverter-turleri", permanent: true },
  { source: "/rehber/optimizer-nedir-ne-ise-yarar", destination: "/rehber/optimizer", permanent: true },
  { source: "/rehber/panel-gucu-wp-peak-watt-ne-anlama-gelir", destination: "/rehber/panel-gucu", permanent: true },
  { source: "/rehber/batarya-depolama-sistemi-ne-zaman-gerekir", destination: "/rehber/batarya", permanent: true },
  { source: "/rehber/off-grid-sistem-nedir", destination: "/rehber/off-grid", permanent: true },
  { source: "/rehber/akilli-sayac-nedir", destination: "/rehber/akilli-sayac", permanent: true },
  { source: "/rehber/panel-verimi-zamanla-ne-kadar-duser", destination: "/rehber/panel-omru", permanent: true },
  { source: "/rehber/sistem-performansi-nasil-izlenir", destination: "/rehber/performans-takibi", permanent: true },
  { source: "/rehber/inverter-arizasi-belirtileri", destination: "/rehber/inverter-arizasi", permanent: true },
  { source: "/rehber/panelleri-kendim-temizleyebilir-miyim", destination: "/rehber/panel-temizligi", permanent: true },
  { source: "/rehber/inverter-kac-yilda-bir-degisir", destination: "/rehber/inverter-omru", permanent: true },
  { source: "/rehber/panel-acisi-yonu-nasil-optimize-edilir", destination: "/rehber/panel-acisi", permanent: true },
  { source: "/rehber/golgeleme-analizi-nasil-yapilir", destination: "/rehber/golgeleme", permanent: true },
  { source: "/rehber/string-tasarimi-nedir", destination: "/rehber/string-tasarimi", permanent: true },
  { source: "/rehber/fabrika-depo-catisina-kurulumda-nelere-dikkat-edilir", destination: "/rehber/fabrika-catisi", permanent: true },
  { source: "/rehber/sogutmali-depo-ozel-catida-ges-kurulumu", destination: "/rehber/soguk-hava-deposu", permanent: true },
  { source: "/rehber/gunes-enerjisi-sistemi-gayrimenkul-degerini-etkiler-mi", destination: "/rehber/gayrimenkul-degeri", permanent: true },
  { source: "/rehber/kocaeli-marmara-bolgesi-gunes-enerjisi-icin-uygun-mu", destination: "/rehber/marmara", permanent: true },
];

// Old social preview image URLs must still resolve after their page moves.
export function canonicalPublicPath(path: string): string {
  const redirect = publicRedirects.find(item => item.source === path);
  if (redirect) return redirect.destination;
  return path.startsWith("/ges-kurulumu/") ? path.replace("/ges-kurulumu/", "/bolgeler/") : path;
}
